- hosts: 127.0.0.1
  vars:
    artifactName: {{ ansible_env.ARTIFACT_NAME }}
    artifactVersion: {{ ansible_env.ARTIFACT_VERSION }}
    apsAppName: {{ ansible_env.APP_NAME }}
    apsPackageName: com/alfresco/aps
    apsApiUser: admin@app.activiti.com
    apsApiPassword: admin
    apsHost: localhost
    apsPort: 8080
    apsApiUri: activiti-app/api/enterprise
    artifactoryHost: localhost
    artifactoryPort: 8082
    artifactoryUri: artifactory/libs-release-local
    checkoutLocation: C:\Windows\Temp
    renewIdm: true
  # App Deployment - this needs to happen only once. So you don't need to do this against all nodes.
  name: Download App Zip
  tasks:
  - win_get_url:
      url: 'http://{{artifactoryHost}}:{{artifactoryPort}}/{{artifactoryUri}}/{{apsPackageName}}/{{artifactName}}/{{artifactVersion}}/{{artifactName}}-{{artifactVersion}}-App.zip'
      dest: '{{checkoutLocation}}/{{artifactName}}-{{artifactVersion}}-App.zip'                                                               